#!/bin/bash

echo "════════════════════════════════════════════════════════════════════════════════"
echo "RESEARCHFLOW - COMPLETE WORKFLOW TEST"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ ALL FIXES APPLIED:"
echo "   1. Orchestrator: Added 'delivery' approval type routing"
echo "   2. QA Agent: Passes data_package to delivery_agent"
echo "   3. Delivery Agent: Defensive validation"
echo ""
echo "✅ APPS RESTARTED WITH FIXED CODE:"
echo "   - Researcher Portal: http://localhost:8501"
echo "   - Admin Dashboard: http://localhost:8502"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo "TESTING INSTRUCTIONS"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  IMPORTANT: Do NOT look at old stuck requests!"
echo "   The old requests (like REQ-20251105-C1F1F66B) were created BEFORE the fixes."
echo "   They are permanently stuck and cannot be fixed retroactively."
echo ""
echo "✅ SUBMIT A BRAND NEW REQUEST:"
echo ""
echo "   1. OPEN RESEARCHER PORTAL:"
echo "      http://localhost:8501"
echo ""
echo "   2. FILL IN THE FORM:"
echo "      Request: \"I need demographics (family name, given name, date of birth, address)"
echo "               for male patients with diabetes diagnosis.\""
echo "      Name: Test User"
echo "      Email: test@hospital.org"
echo "      Department: Testing"
echo "      IRB Number: IRB-TEST-001"
echo ""
echo "   3. CLICK 'Submit Request'"
echo "      The request will be submitted and you'll see a new request ID"
echo ""
echo "   4. OPEN ADMIN DASHBOARD:"
echo "      http://localhost:8502"
echo ""
echo "   5. APPROVE PHENOTYPE SQL:"
echo "      - Go to 'Pending Approvals' tab"
echo "      - Find your request's 'phenotype_sql' approval"
echo "      - Click 'Approve'"
echo "      - Submit"
echo ""
echo "   6. WAIT FOR WORKFLOW TO PROGRESS:"
echo "      Workflow will auto-advance through preview → QA → full extraction → final QA"
echo ""
echo "   7. APPROVE DELIVERY:"
echo "      - Go back to 'Pending Approvals' tab"
echo "      - Find the 'delivery' approval"
echo "      - Click 'Approve'"
echo "      - Submit"
echo ""
echo "   8. VERIFY COMPLETION:"
echo "      - Check Admin Dashboard → 'All Requests' sidebar"
echo "      - Your request should show state: 'complete'"
echo "      - Check Researcher Portal - should show 'Delivered'"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo "EXPECTED RESULT: Request reaches 'complete' status in both UIs"
echo "════════════════════════════════════════════════════════════════════════════════"
