"""
Test Natural Language to SQL Generation Workflow (Sprint 7.2 Phase 6 port).

End-to-end LangGraph workflow:
1. Submit natural language query
2. requirements_agent extracts structured requirements
3. phenotype_agent generates SQL-on-FHIR query
4. Approval row created for SQL review

Ported from A2A's ResearchRequestOrchestrator per ADR 0024 D3. The A2A
original was already broken on pre-existing schema drift (referenced
`.requirements` and `.report` nested fields that don't exist on current
models — the actual fields are `inclusion_criteria` and `phenotype_sql`
directly on the model). This port also fixes that.

LangGraph workflow runs end-to-end synchronously via `process_new_request`
(with AUTO_APPROVE_FOR_DEV=true skipping HITL pauses). No asyncio.sleep()
between submit and assertion needed — process_new_request awaits full
workflow completion.

Integration test — requires ANTHROPIC_API_KEY and HAPI Postgres :5433.
Marked accordingly so CI can filter.
"""

from __future__ import annotations

import pytest

pytestmark = [
    pytest.mark.integration,
    pytest.mark.requires_api_key,
    pytest.mark.requires_hapi,
]

from sqlalchemy import select

from app.database import get_db_session
from app.database.models import Approval, FeasibilityReport, RequirementsData
from app.langchain_orchestrator.request_facade import LangGraphRequestFacade


@pytest.fixture
async def orchestrator():
    """LangGraph facade for end-to-end NL → SQL flow."""
    facade = LangGraphRequestFacade(use_real_agents=True, use_persistence=True)
    try:
        yield facade
    finally:
        await facade.close()


class TestNaturalLanguageToSQL:
    """End-to-end NL → SQL → approval pipeline through LangGraph."""

    async def test_heart_failure_diabetes_query(self, orchestrator):
        """Heart failure + diabetes 2024 cohort: requirements extracted, SQL generated, approval created."""
        natural_language_query = (
            "I need heart failure patients from 2024 with diabetes. "
            "I want de-identified data including demographics and lab results."
        )
        researcher_info = {
            "name": "Dr. Test Smith",
            "email": "test.smith@hospital.org",
            "department": "Cardiology",
            "irb_number": "IRB-2024-TEST-001",
        }

        request_id = await orchestrator.process_new_request(
            researcher_request=natural_language_query,
            researcher_info=researcher_info,
        )
        assert request_id is not None

        async with get_db_session() as session:
            # Requirements extracted by requirements_agent
            req_row = (
                await session.execute(
                    select(RequirementsData).where(RequirementsData.request_id == request_id)
                )
            ).scalar_one_or_none()
            assert (
                req_row is not None
            ), "RequirementsData row should be created by requirements_agent"

            criteria = " ".join(req_row.inclusion_criteria or []).lower()
            assert any(
                term in criteria for term in ["heart failure", "hf", "chf"]
            ), f"Heart failure missing from inclusion_criteria: {req_row.inclusion_criteria}"
            assert any(
                term in criteria for term in ["diabetes", "dm"]
            ), f"Diabetes missing from inclusion_criteria: {req_row.inclusion_criteria}"

            # Feasibility report + SQL generated by phenotype_agent
            feas_row = (
                await session.execute(
                    select(FeasibilityReport).where(FeasibilityReport.request_id == request_id)
                )
            ).scalar_one_or_none()
            assert (
                feas_row is not None
            ), "FeasibilityReport row should be created by phenotype_agent"
            assert feas_row.phenotype_sql, "phenotype_sql should be generated"

            sql_lower = feas_row.phenotype_sql.lower()
            assert "select" in sql_lower, "SQL missing SELECT clause"
            assert "from" in sql_lower, "SQL missing FROM clause"
            assert "patient" in sql_lower, "SQL doesn't query patient table"

            # Approval row for phenotype_sql (status may be 'approved' if
            # AUTO_APPROVE_FOR_DEV is on; 'pending' otherwise — both prove
            # the gate fired)
            approval_row = (
                await session.execute(
                    select(Approval).where(
                        Approval.request_id == request_id,
                        Approval.approval_type == "phenotype_sql",
                    )
                )
            ).scalar_one_or_none()
            assert approval_row is not None, (
                "phenotype_sql Approval row should exist (LangGraph fires the gate "
                "regardless of AUTO_APPROVE_FOR_DEV; only whether it pauses differs)"
            )

    async def test_elderly_female_patients_query(self, orchestrator):
        """Female patients age 65+: gender + age criteria preserved through SQL generation."""
        request_id = await orchestrator.process_new_request(
            researcher_request="I need female patients over age 65",
            researcher_info={
                "name": "Dr. Jane Doe",
                "email": "jane.doe@hospital.org",
                "irb_number": "IRB-2024-TEST-002",
            },
        )

        async with get_db_session() as session:
            feas_row = (
                await session.execute(
                    select(FeasibilityReport).where(FeasibilityReport.request_id == request_id)
                )
            ).scalar_one_or_none()

        assert feas_row is not None, "FeasibilityReport row should exist"
        assert feas_row.phenotype_sql, "phenotype_sql must be generated"

        sql_lower = feas_row.phenotype_sql.lower()
        assert (
            "gender" in sql_lower or "sex" in sql_lower
        ), f"SQL missing gender/sex filter: {feas_row.phenotype_sql[:200]}"
        assert any(
            term in sql_lower for term in ["age", "birthdate", "birth_date", "65"]
        ), f"SQL missing age filter: {feas_row.phenotype_sql[:200]}"

    async def test_sql_syntax_validation(self, orchestrator):
        """Generated SQL has well-formed clauses (structural check, no execution)."""
        request_id = await orchestrator.process_new_request(
            researcher_request="I need COVID-19 patients from 2023",
            researcher_info={
                "name": "Dr. Test",
                "email": "test@hospital.org",
                "irb_number": "IRB-2024-TEST-003",
            },
        )

        async with get_db_session() as session:
            feas_row = (
                await session.execute(
                    select(FeasibilityReport).where(FeasibilityReport.request_id == request_id)
                )
            ).scalar_one_or_none()

        assert feas_row is not None
        assert feas_row.phenotype_sql, "phenotype_sql must be generated"

        sql = feas_row.phenotype_sql
        sql_lower = sql.lower()

        # Basic SQL structure
        assert "select" in sql_lower, "SQL missing SELECT clause"
        assert "from" in sql_lower, "SQL missing FROM clause"

        # Balanced parens (cheap structural sanity check)
        assert sql.count("(") == sql.count(
            ")"
        ), f"Unbalanced parentheses: {sql.count('(')} `(` vs {sql.count(')')} `)`"
