---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	new_request(new_request)
	requirements_gathering(requirements_gathering)
	complete(complete)
	__end__([<p>__end__</p>]):::last
	__start__ --> new_request;
	new_request --> requirements_gathering;
	requirements_gathering -. &nbsp;wait_for_input&nbsp; .-> __end__;
	requirements_gathering -.-> complete;
	complete --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

